### PR TITLE
Update `string-width` to fix vulnerable `ansi-regex`

### LINKED ISSUE #9: This package relies on vulnerable dependencies
The package currently depends on v2 of `string-width`, which transitively depend on `ansi-regex` v3, for which Snyk reports a [ReDoS vulnerability](https://app.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908).

It would be great to upgrade to the v4 of `string-width`, which uses a version of `ansi-regex` that has been patched (upgrading to `string-width` v5 is harder, as it is an ES module and so might require migrating to ESM too, which would require a major version, which then would still justify upgrading to v4 first to fix things in the existing major version)

### PR DESCRIPTION
**Pull request by StudioMaX**
> The package currently depends on v2 of `string-width`, which transitively depend on `ansi-regex` v3, for which Snyk reports a [ReDoS vulnerability](https://app.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908).
Dependency tree:
```
@nuxt/friendly-errors-webpack-plugin@^2.5.1
  > string-width@^2.0.0
    > strip-ansi@^4.0.0
      > ansi-regex@^3.0.0
```
GitHub Advisory Database: https://github.com/advisories/GHSA-93q8-gq69-wqmw

Fixes https://github.com/nuxt/friendly-errors-webpack-plugin/issues/9

Local tests passed successfully

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]

**Comment by tony-tran** [comment]
Hi,

Do you know when the release will be build ? 

Thx.

**Comment by StudioMaX** [comment]
Sorry for ping @clarkdo could you tag a new release?

**Comment by clarkdo** [comment]
Sorry for the delay, I’ll make a release shortly

**Comment by clarkdo** [comment]
v2.5.2 is published now.

**Pull request merged**
